baseURL: https://phase.blog/reference
languageCode: en-us
title: Phase
theme: book
paginate: 3
pygmentsUseClasses: true
canonifyURLs: true
relativeURLs: true

params:
  BookTheme: auto
  BookMenuBundle: /menu
  label:
    icon: "/phase_logo.svg"
    iconHeight: 55px
    text: " "

menu:
  main:
    - name: API Docs
      url: /api
    - name: Reference
      url: /reference
    - name: Blog
      url: /
